### ISSUE TITLE
Cannot create iteractive bash console

### ISSUE THREAD

**Issue by jusso-dev** [bashNinja-dockers/docker-pritunl#1]
I've tried to create a interactive bash session with the container so i can change the default mongo instance, but the container just hangs when I type:

docker exec -it <Container-ID> /bin/bash

i've tried also docker exec -it <Container-ID> bash with the same result, do you have any ideas? I realise that this may be related to the Linux destro the image was built on, and the command may be different. Alternatively, if you have any advice on how i can easily change the mongo connection that would be appreciated as well.

Thanks,
Justin

**Comment by miketweaver** [comment]
This is a docker question. Please refer to the docker documentation:

> $ docker exec -it ubuntu_bash bash
>This will create a new Bash session in the container ubuntu_bash.

https://docs.docker.com/engine/reference/commandline/exec/#examples

**Comment by jusso-dev** [comment]
Actually never mind i'm an idiot, i release the Docker file is copying the root folder which has a pritunl.conf file where i can change the default mongo instance

**Comment by miketweaver** [comment]
As to that `pritunl.conf` question. If you mount `/config` like the instructions, you can just edit the `pritunl.conf` file that is 'generated' and placed into that mountpoint.
